language: go
go:
  - tip
addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - psql -c 'create database conveyor_test;' -U postgres
  - psql -c "create role conveyor login password 'testing'" -U postgres
  - psql -c 'alter database conveyor_test owner to conveyor' -U postgres
  
before_install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go get golang.org/x/tools/cmd/cover

script:
  - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
